### ISSUE TITLE
Capture sponsor details

### ISSUE THREAD

**Issue by gilesdring** [open-innovations/leeds-digital-festival-data#11]

**Comment by gilesdring** [comment]
At the moment this is a simple json with counts. Should we instead arrays of sponsor details for presentation along the lines of https://open-innovations.org/dashboard/#sponsors https://open-innovations.org/dashboard/#sponsors.

We will be able to derive counts from this, and would be able to do more interesting things with this.

**Comment by gilesdring** [comment]
@slowe I've added this sponsors file - very simple for now (just counts of sponsors by category). Could you add this to the dashboard?

**Comment by slowe** [comment]
Done
